core_common_homepage:
    path:     /
    defaults: { _controller: CoreCommonBundle:Main:index }

core_common_get_token:
    path:     /token/
    defaults: { _controller: CoreCommonBundle:Main:getToken }

core_common_test_case:
    path:     /test-case/
    defaults: { _controller: CoreCommonBundle:Main:test }

core_common_test_success:
    path:     /test-case/success/
    defaults: { _controller: CoreCommonBundle:Main:success }

core_common_test_results:
    path:     /test-case/results/
    defaults: { _controller: CoreCommonBundle:Main:results }

core_common_test_results_streamed:
    path:     /test-case/results/stream
    defaults: { _controller: CoreCommonBundle:Main:streamedResults }


core_common_test_results_api:
    path:     /api/{token}
    defaults: { _controller: CoreCommonBundle:Main:getTestCasesApi }

