core_common_homepage:
    path:     /
    defaults: { _controller: CoreCommonBundle:Main:index }

core_common_get_token:
    path:     /{token}
    defaults: { _controller: CoreCommonBundle:Main:getToken }
