<?php

namespace Core\CommonBundle\Repository;

/**
 * HtmlElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HtmlElementRepository extends \Doctrine\ORM\EntityRepository
{
}
