<?php

namespace Core\CommonBundle\Repository;

/**
 * InputVectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InputVectorRepository extends \Doctrine\ORM\EntityRepository
{
}
