<?php

namespace Core\CommonBundle\Repository;

/**
 * TestCaseDescriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCaseDescriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
