<?php

namespace Core\CommonBundle\Repository;

/**
 * TestCaseMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCaseMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
