<?php

namespace Core\CommonBundle\Repository;

/**
 * TestCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestCaseRepository extends \Doctrine\ORM\EntityRepository
{
}
