<?php

namespace Core\CommonBundle\Repository;

/**
 * UserAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
