<?php

namespace Core\CommonBundle\Repository;

/**
 * VectorCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VectorCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
